# Generated by Django 3.1.4 on 2020-12-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_and_anime', '0002_remove_contect_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contect',
            name='desc',
            field=models.CharField(default='', max_length=1100),
        ),
    ]
