# Generated by Django 3.1.4 on 2020-12-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_and_anime', '0003_contect_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
